### ISSUE TITLE
Epiphany crashes on elementary.io

### ISSUE THREAD

**Issue by aral** [elementary/browser#2]
## What happens

Epiphany crashes while browsing the elementary.io home page.

## What should happen

Nothing extraordinary.

## What actually happens

![Screenshot from 2020-12-09 10-54-15@2x](https://user-images.githubusercontent.com/41798/101622363-dc9a8780-3a0e-11eb-87a7-e232410c83d3.png)

The browser tab crashes.

## Steps to Reproduce

1. Open https://elementary.io in Epiphany.
2. Scroll down and around a bit.

## Platform Information

```
OS: elementary OS 5.1.7 Hera x86_64 
Host: LabTop Mk IV 
Kernel: 5.4.0-56-generic 
Uptime: 23 hours, 52 mins 
Packages: 1719 
Shell: zsh 5.4.2 
Resolution: 3840x2160 
DE: Pantheon 
WM: Mutter(Gala) 
Terminal: io.elementary.t 
CPU: Intel i7-10710U (12) @ 4.700GHz 
GPU: Intel Device 9bca 
Memory: 4672MiB / 15883MiB 
```

**Comment by cassidyjames** [comment]
I have also seen this lately. I think there may have been a problematic update to Epiphany lately, as I also get more crashes on other sites that are not doing anything particularly spectacular.

**Comment by selwynorren** [comment]
Seems I am having the same issue. I cannot view any web site at all. I get the same crash instance

**Comment by selwynorren** [comment]
I read somewhere for Elementary S 6 missing files were update that fixed these crashes, but I have just installed the latest daily build (16 May) and I am still not able to browser websites. I had to install Firefox again, just to get here.

Interestingly, if I do a google search, that result page loads fine, however if I click a link, that breaks.

I can get to github, however the moment I try and search a repository, then I get the same error.

**Comment by KarkanAlzwayed** [comment]
This issue is happening on EOS 6 beta. For me, it doesn't work at all. It only shows a website for a brief second then crashes like so (on every single website I try to visit)
![Screenshot from 2021-05-20 11-42-51@2x](https://user-images.githubusercontent.com/49320606/119009439-1d54e000-b961-11eb-9502-62416fcce0a5.png)

**Comment by cassidyjames** [comment]
@KarkanAlzwayed this is a different issue; please see https://github.com/elementary/flatpak-platform/issues/32

**Comment by KarkanAlzwayed** [comment]
@cassidyjames thank you. Just didn't know where to find/report it as I can't find "epiphany" in the "send feedback" section in settings/system.

**Comment by cassidyjames** [comment]
I can no longer reproduce this in the Flatpak. If you're on elementary OS 5, I would recommend installing GNOME Web from Flathub for the latest version; on elementary OS 6 and newer, it comes with the Flatpak version out of the box.

**Comment by selwynorren** [comment]
Okay thanks @cassidyjames Like @KarkanAlzwayed I cannot find the web browser in give feedback to report is correctly. In my Work horse machine, Epiphany works just fine and no issues with it. I have Elementary OS 6 (Latest daily build installed yesterday) and Epiphany is completely unusable. But will report to the link provided

**Comment by cassidyjames** [comment]
@selwynorren if you're on a recent daily, you should be able to run:

```
flatpak install --system freedesktop org.freedesktop.Platform.GL.default//20.08
```

to resolve it.

**Comment by Marukesu** [comment]
@selwynorren can you run `flatpak info --system org.gnome.Epiphany` and confirm that the daily branch is the installed one?

Also run `flatpak info --system org.gnome.Epiphany.Locale io.elementary.Platform.Locale` and confirm that they have the correct locale installed, WebKit won't load any page if they can't find the correct locale.

**Comment by selwynorren** [comment]
> @selwynorren if the problem persists, can you run `flatpak info --system org.gnome.Epiphany` and confirm that the daily branch is the installed one?
> 
> Also run `flatpak info --system org.gnome.Epiphany.Locale io.elementary.Platform.Locale` and confirm that they have the correct locale installed, WebKit won't load any page if they can't find the correct locale.

Howdy, so the new daily image I downloaded was elementaryos-6.0-daily.20210516.iso. Out the box, I get this error reported, after a few updates however, it all seems to update and then work, but it does not work out of the box. Right now if I run flatpak info --system org.gnome.Epiphany
This is the result:

```
GNOME Web - Web Browser for GNOME

          ID: org.gnome.Epiphany
         Ref: app/org.gnome.Epiphany/x86_64/master
        Arch: x86_64
      Branch: master
     Version: 3.38.3
     License: GPL-3.0+
      Origin: appcenter
  Collection: 
Installation: system
   Installed: 9.0 MB
     Runtime: io.elementary.Platform/x86_64/daily
         Sdk: io.elementary.Sdk/x86_64/daily

      Commit: c72b1619a3d50e3fd2625ab87524a5c1686115104653960fd5ec5489b4d3d7cf
      Parent: cbfe7ce313f8ccb3ad086f0852449b69767d389da44fc465c2b6a0b31f4e22f1
     Subject: Export org.gnome.Epiphany
        Date: 2021-05-14 20:16:28 +0000
```

When I run the locale command: flatpak info --system org.gnome.Epiphany.Locale io.elementary.Platform.Locale I get the following result:
```
error: org.gnome.Epiphany.Locale/*unspecified*/io.elementary.Platform.Locale not installed
```
Finally to confirm on my Elementary OS 5.1.7 I do not have this issue, this is only on my Elementary OS 6 Early release where this is a problem. Epiphany is not an option to give feedback on, hence why we posted ti here. Should I rather report it here: https://github.com/elementary/flatpak-platform/issues/32
